config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  resources :posts
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,       only: [:create, :destroy]
  
  root 'pages#index'

  get 'home' => 'pages#home'

  get '/user/:id' => 'pages#profile'

  get 'explore' => 'pages#explore'

end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 500 }
  
  default_scope -> { order(created_at: :desc) } 
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         has_many :posts, dependent: :destroy
         has_many :active_relationships, class_name: "Relationship", foreign_key: 'follower_id', dependent: :destroy
         has_many :passive_relationships, class_name: "Relationship", foreign_key: 'followed_id', dependent: :destroy
         #active relationships is where the user is following
         #passive is where the user is being followed
         
         has_many :following, through: :active_relationships, source: :followed
         has_many :followers, through: :passive_relationships, source: :follower

         #denotes the follower/following relationships
         def follow(other)
           active_relationships.create(followed_id: other.id)
         end
         
         def unfollow(other)
           active_relationships.find_by(followed_id: other.id).destroy
         end
         
         def following?(other)
           following.include?(other)
         end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
  end

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def about
  end
end

app/controllers/pages_controller.rb
# The pages controller contains all of the code for any page inside of /pages
class PagesController < ApplicationController
  
  # back-end code for pages/index
  def index
    #no specific ruby code is needed for this page
  end

  # back-end code for pages/home
  def home
    following = Array.new
    #checks the database for who the user is following.
    for @f in current_user.following do
      following.push(@f.id)
    end
    
    #only posts from users in the following array are collected.
    @posts = Post.all.where("user_id = ?", following)
    @newPost = Post.new
  end

  # back-end code for pages/profile
  def profile
    # grab the username from the URL as :id
    if (User.find_by_username(params[:id]))
      @username = params[:id]
    else 
      # redirect to root
      redirect_to root_path, :notice=> "User not found!" 
    end
    
    #only posts by that specific user are collected from the database
    @posts = Post.all.where("user_id = ?", User.find_by_username(params[:id]).id)
    @newPost = Post.new
  end

  # back-end code for pages/explore
  def explore
    #all posts are collected from the database
    @posts = Post.all
    @newPost = Post.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end
    
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id
        respond_to do |f|
            if (@post.save)
                f.html{ redirect_to "", notice: "Posted!" }
            else
                f.html{ redirect_to "", notice: "Error" }
            end
        end
    end
    
    private
    def post_params
        params.require(:post).permit(:user_id, :content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

    def create
        user = User.find(params[:followed_id])
        current_user.follow(user)
        redirect_to(:back)
    end
    
    def destroy
        user = Relationship.find(params[:id]).followed
        current_user.unfollow(user)
        redirect_to(:back)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
    end
    
    def resource_class 
        User 
    end
    
    def resource
        @resource ||= User.new
    end
    
    def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
    <footer>
      <div class = 'body-footer'>
        Copyright
      </div>
    </footer>

app/views/layouts/_nav.html.erb
<%-# Renders different navigation bars depending on if the user is signed in -%>

<% if !user_signed_in? %>
  <%-# Renders the guest nav bar found in views/layouts/_nav_guest -%>
  <%= render 'layouts/nav_guest' %>
<% else %>
  <%-# Renders the user nav bar found in views/layouts/_nav_user -%>
  <%= render 'layouts/nav_user' %>
<% end %>

app/views/layouts/_nav_guest.html.erb
<!-- Navbar used for when a guest is using the system-->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("Sign Up", new_user_registration_path) %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("Log In", new_user_session_path) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<!-- Navbar used for when a user is signed in -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home">
        <span class= "glyphicon glyphicon-fire" aria-hidden="true"></span>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/home"><span class= "glyphicon glyphicon-home" aria-hidden="true"></span> Home</a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li><a href="/explore"><span class= "glyphicon glyphicon-globe" aria-hidden="true"></span>Explore</a></li>
      </ul>
      <ul class = 'nav navbar-nav navbar-right'>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/user/<%= current_user.username %>">Profile</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Edit Profile', edit_user_registration_path) %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to('Log Out', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>

<div class="container">
  <span class="notice"><%= notice %></span>
  <span class="alert"><%= alert %></span>
  <%= yield %>
</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/explore.html.erb
<div class='row'>
    <div class='col-xs-12'>
      <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal"><span class= "glyphicon glyphicon-question-sign" aria-hidden="true"></span></button>
      <%= render '/components/post_form' %>
      <% for @p in @posts %>
      <div class="panel panel-default post-panel">
        <div class="panel-body">
          <div class = "col-xs-1">
            <img src="/Default-Avatar.jpg" height="50px" width="50px"></img>
          </div>
          
          <div class "col-xs-11">
            <div class = "posts">
              <a href = "/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %><span class = "post-time"> <%= @p.created_at.to_formatted_s(:short)%></span></a>
              <p><%= @p.content %></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Explore The Network</h4>
      </div>
      <div class="modal-body">
        <p>
          Find some new people, make some new friends. On the Explore page, every single post by every single user is displayed for the world to see. From here you can view people’s profiles and maybe even give them a follow!
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/pages/home.html.erb
<div class='row'>
    <div class='col-xs-4'>
        <div class="panel panel-default">
          <div class="panel-body">
            <center><img src="/Default-Avatar.jpg" height="200px" width="200px" class="rounded-img">
            <!-- Renders the stats partial -->
            <p><%= render '/components/stats' %></p>
            <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal"><span class= "glyphicon glyphicon-question-sign" aria-hidden="true"></span></button>
            </center>
          </div>
        </div>
    </div>
    <div class='col-xs-8'>
      <!-- Renders the post-form partial -->
      <%= render '/components/post_form' %>
      <% for @p in @posts %>
      <div class="panel panel-default post-panel">
        <div class="panel-body">
          <div class = "col-xs-1">
            <img src="/Default-Avatar.jpg" height="50px" width="50px"></img>
          </div>
          
          <div class "col-xs-11">
            <div class = "posts">
              <a href = "/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %><span class = "post-time"> <%= @p.created_at.to_formatted_s(:short)%></span></a>
              <p><%= @p.content %></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Your Home</h4>
      </div>
      <div class="modal-body">
        <p>
          Welcome to Your Home page. Here at your Home page you will be able to post and view your number of following and followers.
          The posts that you see on Home will be that of those you are following. Only you can say who gets to be in your Home.
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

app/views/pages/index.html.erb
<% if !user_signed_in? %><!-- Only if user is not signed in. -->
    <style>
        body {
            background: linear-gradient(
                rgba(0,0,0,0.1),
                rgba(0,0,0,0.1)) , url("/Mountain.jpg") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
        }
    </style>
    <div class="jumbotron">
      <div class="container">
          <h4>Welcome to</h4><h1> The Network</h1>
          <p><a class="btn btn-primary btn-lg" href="https://docs.google.com/a/parra.catholic.edu.au/document/d/10QQaL5KgHP-L-EqwlA0QAl2S9rdxY0V2W9CEHWC38tI/edit?usp=sharing" role="button">Learn more</a></p>
      </div>
    </div>
    
    <div class = 'row'>
        <div class = "col-xs-3">
          <div class = 'jumbotron'>
            <h2>Sign up</h2>
            <!-- Forms for the Sign Up and Sign in page on landing page -->
            <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
              <%= devise_error_messages! %>
              
              <div><%= f.label :username %><br />
              <%= f.text_field :username %></div>
              
              <div><%= f.label :email %><br />
              <%= f.email_field :email %></div>
            
              <div><%= f.label :password %><br />
              <%= f.password_field :password %></div>
            
              <div><%= f.label :password_confirmation %><br />
              <%= f.password_field :password_confirmation %></div>
            
              <div><%= f.submit "Sign up" %></div>
            <% end %>
            
            <%= render "devise/shared/links" %>
          </div>
        </div>
        <div class = "col-xs-3">
          <div class="jumbotron">
            <h2>Log in</h2>
            
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="field">
                <%= f.label :email %><br />
                <%= f.email_field :email%>
              </div>
            
              <div class="field">
                <%= f.label :password %><br />
                <%= f.password_field :password, autocomplete: "off" %>
              </div>
            
              <% if devise_mapping.rememberable? -%>
                <div class="field">
                  <%= f.check_box :remember_me %>
                  <%= f.label :remember_me %>
                </div>
              <% end -%>
            
              <div class="actions">
                <%= f.submit "Log in" %>
              </div>
            <% end %>
            
            <%= render "devise/shared/links" %>
          </div>
        </div>
    </div>

<% else %> <!-- Renders the home, bypasses landing if user is already signed in -->
    <script>document.location = "/home"</script>
<% end %>

app/views/pages/profile.html.erb
<div class='row'>
    <div class='col-xs-3'>
        <div class="panel panel-default">
          <div class="panel-body">
            <center><img src="/Default-Avatar.jpg" height="200px" width="200px" class="rounded-img">
            <%= render '/components/follow_button', :user => User.find_by_username(params[:id]) %>
            <%= render '/components/stats' %>
            <!-- Trigger the modal with a button -->
            <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal"><span class= "glyphicon glyphicon-question-sign" aria-hidden="true"></span></button>
            </center>
          </div>
        </div>
    </div>
    <div class='col-xs-7'>
      <!-- Only renders if the user is on their own profile. -->
      <% if current_user.username == User.find_by_username(params[:id]).username %>
        <%= render '/components/post_form' %>
      <% end %>
      <!-- Ruby loop to trigger for all the posts necessary -->
      <% for @p in @posts %>
      <div class="panel panel-default post-panel">
        <div class="panel-body">
          <div class = "col-xs-1">
            <img src="/Default-Avatar.jpg" height="50px" width="50px"></img>
          </div>
          
          <div class "col-xs-11">
            <div class = "posts">
              <!-- Accesses database to find the post's user and created date -->
              <a href = "/user/<%= User.find(@p.user_id).username %>"><%= User.find(@p.user_id).username %><span class = "post-time"> <%= @p.created_at.to_formatted_s(:short)%></span></a>
              <p><%= @p.content %></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class='col-xs-2'>
        <div class="panel panel-default">
          <div class="panel-body">
            <center>
              <p>Posts</p>
              <strong><%= User.find_by_username(params[:id]).posts.count %></strong>
            </center>
          </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Your Profile</h4>
      </div>
      <div class="modal-body">
        <p>
          Your Profile is how others will see you, Make it count. As well as posting and seeing your follower-following ratio you will also get to see the number of Posts you make.
          Only your posts will be on your profile. Here people can get a clear indication of who you are. Think of it like your brain!
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>